#!/bin/python3

import sys
import numpy as np


def bubble_sort(L):
    L = L.copy()
    n = len(L)

    for _ in range(n):
        swapped = False
        for i in range(n - 1):
            if L[i] > L[i + 1]:
                L[i], L[i + 1] = L[i + 1], L[i]
                swapped = True
            # print(i, L[i], L[i + 1])

        if not swapped:
            break

    return L


if __name__ == "__main__":
    A = np.array(sys.argv[1:]).astype(float)
    print(bubble_sort(A))
